unet_lr = 0.0001
network_module = "networks.lora"
network_dim = 32
network_alpha = 2.0
network_train_unet_only = true
no_half_vae = true

[sd_models_arguments]
v2 = false
v_parameterization = false
pretrained_model_name_or_path = "/data/models/Stable-diffusion/milkyWonderland_v40.safetensors"

[dataset_arguments]
cache_info = false
shuffle_caption = false
enable_wildcard = false
color_aug = false
flip_aug = false
random_crop = false
debug_dataset = false
resolution = "512"
cache_latents = true
vae_batch_size = 4
cache_latents_to_disk = true
enable_bucket = false
bucket_no_upscale = false

[training_arguments]
output_dir = "/data/models/Lora"
output_name = "my-lora-v1"
save_state_to_huggingface = false
resume_from_huggingface = false
async_upload = false
save_precision = "fp16"
save_every_n_epochs = 1
save_state = false
save_state_on_train_end = false
train_batch_size = 1
max_token_length = 150
mem_eff_attn = false
torch_compile = false
dynamo_backend = "inductor"
xformers = true
sdpa = false
max_train_steps = 2000
max_train_epochs = 5
persistent_data_loader_workers = false
seed = 42
gradient_checkpointing = false
mixed_precision = "fp16"
full_fp16 = false
full_bf16 = false
fp8_base = false
ddp_gradient_as_bucket_view = false
ddp_static_graph = false
logging_dir = "/data/training/logs"
log_with = "tensorboard"
log_prefix = "my-lora-v1-"
noise_offset_random_strength = false
ip_noise_gamma_random_strength = false
zero_terminal_snr = false
loss_type = "l2"
huber_schedule = "snr"
lowram = false
highvram = false
sample_at_first = false
sample_sampler = "euler_a"
output_config = false

[optimizer_arguments]
optimizer_type = "AdamW"
use_8bit_adam = false
use_lion_optimizer = false
learning_rate = 4e-7
max_grad_norm = 0.0
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 400

[config_arguments]
dataset_config = "/data/training/dataset.toml"

[sd_saving_arguments]
save_model_as = "safetensors"