repo_id = "SmilingWolf/wd-v1-4-convnext-tagger-v2"
model_dir = "/data/training/wd14_tagger_model"
force_download = false
batch_size = 4
thresh = 0.35
recursive = false
remove_underscore = false
debug = false
frequency_tags = false
onnx = true
append_tags = false
use_rating_tags = false
use_rating_tags_as_last_tag = false
character_tags_first = false
character_tag_expand = false

[dataset_arguments]
train_data_dir = "/data/training/my_data"
caption_extension = ".caption"
caption_separator = ", "

[training_arguments]